kind: Service
apiVersion: v1
metadata:
  name: fleetman-webapp
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 30080

---

kind: Service
apiVersion: v1
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queue
  type: NodePort
  ports:
    - name: http
      port: 8161
      nodePort: 30010
